# Generated by Django 3.2.8 on 2021-11-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uk_regions', '0002_auto_20211103_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioncenter',
            name='id',
        ),
        migrations.AddField(
            model_name='regioncenter',
            name='this_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
