# Generated by Django 3.2.8 on 2021-11-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uk_regions', '0003_auto_20211103_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterRegional',
            fields=[
                ('this_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regioncenter', to='uk_regions.redickoatuuregion', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Обласной центр',
                'verbose_name_plural': 'Обласные центры',
            },
        ),
    ]
