# Generated by Django 3.2.8 on 2021-11-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uk_regions', '0005_centerregional_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regioncenter',
            name='region',
        ),
    ]
